[project]
name = "alor_py"
dynamic = ["version"]
dependencies = [
    "pytz",
    "requests",
    "websockets",
    "pandas==2.1.4"
]
description = "Библиотека-обертка, которая позволяет работать с функционалом Alor OpenAPI V2 брокера Алор из Python"
readme = "README.md"
